spring.application.name=PawFectCare-BackEnd
# Configuracion de la base de datos PostgreSQL para produccion usando la cadena de conexion proporcionada por Azure
# spring.datasource.url=jdbc:postgresql://pawfectcare-server.postgres.database.azure.com:5432/pawfectcare-database&spring.datasource.username=ntyvmihloj&spring.datasource.password=XBu$JpAmvanmb6eW&spring.datasource.driver-class-name=org.postgresql.Driver&spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=${PAWFECTCARE_CONNECTIONSTRING}
spring.datasource.url=jdbc:postgresql://pawfectcare-server.postgres.database.azure.com:5432/pawfectcare-database?sslmode=require
spring.datasource.username=ntyvmihloj
spring.datasource.password=XBu$JpAmvanmb6eW
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# JWT Configuration
authorization.jwt.secret="F-dsYg9omWotK3hD9cyXBwaA18Obr99cZQNjIEtgI18="
authorization.jwt.expiration.days=10